services:
  data-loading:
    build:
      context: .
    container_name: data_loading_service
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    working_dir: /app
    volumes:
      - ./src:/app/src:rw
      - ./data:/app/data:rw
      - ./models:/app/models:rw
    command: >
      python -u -m src.data_loading
      --year 2024
      --units B-CPE-100 B-CPE-110
      --data_dir /app/data
      --utils_dir /app/src/utils
    restart: "no"

  model-production:
    build:
      context: .
    container_name: model_production_service
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    working_dir: /app
    volumes:
      - ./src:/app/src:rw
      - ./data:/app/data:rw
      - ./models:/app/models:rw
    command: >
      python -u -m src.model_production_main
      --year 24
      --data_file /app/data/DATA.csv
    restart: "no"
